DcentWallet/info

dapp/en/dapplist.json, dapp/ko/dapplist.json
Flare Network 요청으로 airdrop 이라는 문구를 distribution으로 변경
=> airdrop to distribution

dapp/en/dapplist.json, dapp/ko/dapplist.json
=> preRelease 제거

ftso/providerlist.json
=> FlareFi 파트너icon,twitter 추가

stacking/poollist.json
=> friedger pool 보상 stx 로 수정

stacking/poollist.json
=> Add stacks network

collectables/info.json
=> Collection heco 추가

dapp/en/dapplist.json, dapp/ko/dapplist.json
https://github.com/IotrustGitHub/dcent-dapp-browser/issues/152
=> BUY_iOS 일때 화면 출력

collectables/info.json
=> xdc network info 추가

swap/networkConfig.json
=> #3 swap network add priority for sorting

ftso/providerlist.json
=> Evolve FTSO partner 추가

banner/thin-banner-info-list.json
https://career.dcentwallet.com =>  https://career.iotrust.kr/introduction 변경
=> banner 채용 link 수정

supported_coin.json
=> #51 리플 네트워크 이름 변경 XRP -> XRPL

supported_coin.json
=> 22.11.16 token list updated..

basic-info.json
- flare network 의 이름을 변경했습니다.
- oasys network 의 정보를 추가했습니다.
=> add oasys & change flare network name

stacking/poollist.json
=> 비활성화 옵션 추가

firmwareVersion.md
|v2.25.3|2023-04-11|• XRP Transaction Bug Fix |
=> 하드웨어 펌웨어 버전 정보 업데이트

firmwareVersion.md
=> HAVAH 추가(v2.26.0)

basic-info.json, supported_coin.json
=> - 하바 메인넷 추가

ftso/providerlist.json
=> fix ftso image url

invest-swap/networkConfig.json
invest swap 에서 klaytn 을 klaytn EVM으로 변경
=> #199 Klaytn mainnet을 Klaytn EVM mainnet 으로 변경

invest-swap/networkConfig.json
[engine_ui](https://github.com/IotrustGitHub/dcent-engine-ui/blob/v3-main/common/constants/ethereum_rpc_url.js) 레포지토리 내의 rpc를 참고하여 추가하였습니다.
=> #205 - networkConfig rpc 추가

reseller/reseller-list-en.json
=> crypto agent 리셀러에서 제거

firmwareVersion.md
- Added Hedera signMessage
- fixed typo
=> #252 update firmwareVersion.md

supported_coin.json
[지원 코인 목록 업데이트 문서](https://www.notion.so/iotrust/6d704c389d944ade932a5b419dba1bf8?p=67ec51f2e2ca47aba71c121bdf451b2e&pm=s)를 참고하여 진행했습니다.
=> #261 - 20240319 지원 코인 업데이트

dapp/network_info.json
=> #264 Astar zkEVM 릴리즈

supported_coin.json
- 고객 지원 토큰 추가 0401 업데이트 사항 반영하였습니다.
=> #266 - 20240401 지원 코인 업데이트

supported_coin.json
- https://github.com/IotrustGitHub/dcent-hybrid-common/pull/772 업데이트 사항 반영하였습니다
=> #271 - 20240415 지원 코인 업데이트

supported_coin.json
- https://github.com/IotrustGitHub/dcent-hybrid-common/pull/781 업데이트 사항 반영하였습니다
=> #275 - 20250429 지원 코인 업데이트

coin-info/onchain/README.md, coin-info/onchain/bitcoin.json
=> #280 onchain metainfo - bitcoin

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/791 를 반영하였습니다.
=> #289 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/797 의 업데이트 사항 반영하였습니다.
=> #293 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/807 의 업데이트를 반영하였습니다.
=> #295 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/809 20240722 토큰 추가 업데이트를 반영하였습니다.
=> #298: 지원 코인 업데이트

firmwareVersion.md
- released D’CENT Biometric Firmware v2.30.5
- compactInt parsing 오류 수정
=> #300 update firmwareVersion.md

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/811 해당 업데이트를 반영하였습니다.
=> #302: 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/818 해당 PR을 반영하였습니다.
=> #307: 지원 코인 업데이트

swap-exchange/json/README.service_info.md, swap-exchange/json/service_info.json
=> #309 swap-exchange 서비스 config 추가

reseller/reseller-list-en.json
=> #311 리셀러 목록 수정 및 링크 변경

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/820 해당 PR을 반영하였습니다.
=> #313: 지원 코인 업데이트

dapp/dapp_list_v2.json
- 서비스 제한 property `restrictionPolicy` 추가
- 만약 true면 서비스 제한 조건을 확인해서 처리한다. 
- 언어별 분리된 dapp list를 하나로 통합한 v2 생성
=> Dapp List에 서비스 제한 property 추가 

dapp/dapp_list_v2.json
- dapp list에 pre-swap-x 추가 함
실제 릴리즈시 url 및 preRelease property 변경 필요
=> #316 pre-swap-x 추가 (dapp list)

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/822과 https://github.com/IotrustGitHub/TokenListMaker/pull/7를 반영하였습니다.
=> #323: 지원 코인 업데이트 및 Core, Para 체인이 누락된 부분 업데이트

supported_coin.json
잘못된 생성으로 추가된 테스트넷을 제거합니다.
바로 merge가 되어있었어서 추가 PR 드려요!
=> #323: CORE 테스트넷 제거

dapp/dapp_list_v2.json, swap-exchange/json/service_info.json
서비스 제한 활성화
Swap X 추가
Swap Pre로 변경
Exchange -> Swap X 로 변경
Merge는 제가 진행 하겠습니다.
=> #329 Swap X 상용 릴리즈

swap-exchange/json/swap-exchange-info.json
swap x의 서비스 별 지원 블록체인 리스트 업데이트
=> #336 swap x info 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/827 업데이트를 반영하였습니다.
=> #332: 2024-09-30 지원 코인 업데이트

supported_coin.json
https://www.notion.so/iotrust/113051dc660f80c98882e4661b243f5f?v=113051dc660f81989cc8000c460523de&p=11e051dc660f80c2a942e3a3c57be8cc&pm=s PR을 반영하였습니다.
=> #338: 2024-10-14 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/832 를 반영하였습니다.
=> #340: 2024-10-28 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/835 의 변경 사항을 반영하였습니다.
=> #342: 2024-11-11 지원 코인 업데이트

supported_coin.json
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/842 를 반영하였습니다.
=> #344: 2024-11-25 지원 코인 업데이트

dapp/network_info.json
- Kaia 리브랜딩 적용
- 미지원 EVM 삭제
- JOC, Gravity 추가
- 블록체인 이름 수정
- `-` 를 제거하고 사용자에게 친숙한 명칭으로 변경
=> #351 Kaia 리브랜딩, 미지원 EVM 삭제, JOC, Gravity 추가

swap-exchange/json/swap-exchange-info.json
=> #349 SWAP Solana 상용 준비

firmwareVersion.md
- Added supporting coin : XAHAU(XAH)
=> [Feature] #363: update firmwareVersion.md

supported_coin.json
지난 변경은 한 번 누락되었었네요.. 잊지 않도록 주의하겠습니다.
이번 변경 사항을 포함하여 업데이트하였습니다.
https://github.com/IotrustGitHub/dcent-hybrid-common/pull/854
=> #365: 2024-12-23 지원 코인 업데이트

supported_coin.json
- Creditcoin (Native, EVM)
- Filecoin  (EVM)
=> [Feature] #371: CTC & FIL 추가

supported_coin.json
=> #375: 지원 코인 목록에서 메인넷이 토큰보다 상위에 위치하도록 순서 변경

supported_coin.json
=>  #378: 2025-01-06 지원 코인 업데이트

dapp/network_info.json
=> #390 CTC FIL NERO SONIC Dapp 상용 릴리즈

supported_coin.json
=> #388: 2025-01-20 지원 코인 업데이트

swap-exchange/json/pre/swap-exchange-info-v1.json, swap-exchange/json/pre/swap-exchange-info.json, swap-exchange/json/swap-exchange-info-v1.json, swap-exchange/json/swap-exchange-info.json
=> #395 bitcoin-sv 삭제

swap-exchange/json/pre/swap-exchange-info.json, swap-exchange/json/swap-exchange-info.json
=> #402 v0 mapper 수정

supported_coin.json
- wallet-models 내의 중복 검사가 추가되어, 중복 반영된 토큰은 제거되었습니다.
- 2025-02-03 추가분이 반영되었습니다.
=> #400: 2025-02-03 지원 코인 업데이트

app/event/README.md, app/event/app_event_list.json
- 다크/라이트테마에 따라 bgColor, strokeColor 각각 들고 있게 수정
=> #406: Swap Complete 시에 이벤트 배너 정보 수정

reseller/reseller-list-en.json
연결되지 않거나 판매가 마감된 리셀러 리스트에서 제거하였습니다.
관련 슬랙입니다 : https://iotrust.slack.com/archives/CS6TV554Y/p1739408687291069?thread_ts=1723626822.306239&cid=CS6TV554Y
=> 연결되지 않거나 판매가 마감된 리셀러 제거

supported_coin.json
- wallet-models 내의 name이 변경된 사항도 함께 반영되었습니다.
- e.g) Stellar Lumen -> Stellar
=> #416: [Add Token] 2025-02-17 고객 지원 토큰 추가 내용 반영

firmwareVersion.md, supported_coin.json
- Added Filecoin to the supported_coin.json file.
- update firmwareVersion.md - Added supporting coin: Filecoin (FIL)
=> [Feature] #414 add filecoin

supported_coin.json
LESTER: 5z3iCe53hUANTiG8Js8RjHNE2Arjik7L2CXLyr2rpump
BOTIFY: BYZ9CcZGKAXmN2uDsKcQMM9UnZacija4vWcns9Th69xb
COLLE: AFDzaLz3cQZNWjnWbyq2q81TLVTPbHTbfkj8qKqTk74e
WEPE: 0xccb365d2e11ae4d6d74715c680f56cf58bf4bf10
PLUME: 0x4c1746a800d224393fe2470c70a35717ed4ea5f1
COLLE: 0xc36983d3d9d379ddfb306dfb919099cb6730e355
B3: 0xb3b32f9f8827d4634fe7d973fa1034ec9fddb3b3
WAGC: 0x47e316d1951568b4fbc7a1bcd641c5624a756a05
IOTX: 0xbcbaf311cec8a4eac0430193a528d9ff27ae38c1
XPRT: 0xc7edf7b7b3667a06992508e7b156eff794a9e1c8
XPRT: 0xc7edf7b7b3667a06992508e7b156eff794a9e1c8
COLLE: 0xaeb63742f2c7dd1538bbe2285b6789017a06b58b
USDT: 0x48065fbbe25f71c9282ddf5e1cd6d6a887483d5e
총계: 13
=> #423: [Add Token] 2025-03-04 고객 지원 토큰 추가 내용 반영

swap-exchange/json/beta/swap-exchange-info-v2.json
=> #32 changenow에서 filecoin evm 지원을 위한 하드코딩

swap-exchange/json/swap-exchange-info-v2.json
filecoin 및 filecoin evm 지원 - Prod
=> #428 filecoin & filecoin EVM 지원 - prod

supported_coin.json
BROCCOLI: 0x12b4356c65340fb02cdff01293f95febb1512f3b
WMTX: 0xdbb5cf12408a3ac17d668037ce289f9ea75439d7
COOKIE: 0xc0041ef357b183448b235a8ea73ce4e4ec8c265f
TEL: 0x09be1692ca16e06f536f0038ff11d1da8524adb1
WMTX: 0x3e31966d4f81c72d2a55310a6365a56a4393e98d
COOKIE: 0xc0041ef357b183448b235a8ea73ce4e4ec8c265f
MT: 0xff45161474c39cb00699070dd49582e417b57a7e
WMTX: 0xdbb5cf12408a3ac17d668037ce289f9ea75439d7
XPRT: 0xd454b59f16d42667be2fa55292d16647e27f40c4
CTF: 제거 (마이그레이션)
CTF: r9Xzi4KsSF1Xtr8WHyBmUcvfP9FzTyG5wp
CAR: 7oBYdEhV4GkXC19ZfgAvXpJWp2Rn9pm1Bx2cVNxFpump
총계: 12
=> #436: [Add Token] 2025-03-17 고객 지원 토큰 추가 내용 반영

swap-exchange/json/beta/service_info.json, swap-exchange/json/pre/service_info.json
prod 와 동일한 환경 테스트를 위해 
정책을 활성화 하였습니다.
=> #437 정책을 prod와 동일하게 업데이트

supported_coin.json
WFI: 0x90c48855bb69f9d2c261efd0d8c7f35990f2dd6f
ICE: 0xc335df7c25b72eec661d5aa32a7c2b7b2a1d1874
TUA: 0x36b2269fd151208a4bfc3dea503e0a6f2485fa78
LBTC: 0xecac9c5f704e954931349da37f60e39f515c11c1
FET: 토큰 이름 변경
LBTC: 0xecac9c5f704e954931349da37f60e39f515c11c1
GRT: 0x9623063377ad1b27544c965ccd7342f7ea7e88c7
GRT: 0x8a0cac13c7da965a312f08ea4229c37869e85cb9
ICE: 0x79f05c263055ba20ee0e814acd117c20caa10e0c
VALOR: 0x297e4e5e59ad72b1b0a2fd446929e76117be0e0a
RBNT: 0xb45ffb51984d626ee758b336c61cf20990c6bf13
TUA: 0x791a5c2261823dbf69b27b63e851b7745532cfa2
LBTC: 0x8236a87084f8b84306f72007f36f2618a5634494
FET: 토큰 이름 변경
GRT: c944e90c64b2c07662a292be6244bdf05cda44a7.factory.bridge.near
GRT: 0x5fe2b58c013d7601147dcdd68c143a77499f5531
ALCH: HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump
DOPU: …
=> #447: [Add Token] 2025-03-31 고객 지원 토큰 추가 내용 반영

firmwareVersion.md, supported_coin.json
- v2.34.4
- Added missing Spanish translation
=> [Feature] #497: Update firmwareVersion.md

dapp/network_info.json
=> [Feature] #516: Camp Mainnet preRelease

dapp/network_info.json
- Camp Mainnet, Humanity Protocol, Stable Testnet preRelease 제거
=> [Fearture] #516: preRelease 제거

firmwareVersion.md
- v2.35.0
- Added support for message signing
=> [Feature] #522: Update firmwareVersion.md
